---
title: "Impact of Indian Classical Raga in Immersive Environments on Human Psycho-physiological Parameters"
date: 2023-08-10
author:
  - name: Shilpa Chandra
    affiliation: Indian Institute of Technology Mandi
  - name: Kulbhushan Chand
    url: https://kulbhushanchand.github.io
    orcid: 0000-0003-2042-7063
    affiliation: IIT Mandi iHub and HCI Foundation
  - name: Varun Dutt
    affiliation: Indian Institute of Technology Mandi
categories:
  - Raga bhairavi
  - Indian classical music
  - Heart rate variability
  - DASS
  - Virtual reality
pub-info:
  reference: >-
    Shilpa Chandra, <strong>Kulbhushan Chand</strong>, and Varun Dutt, “Impact of Indian Classical Raga in Immersive Environments on Human Psycho-physiological Parameters,” <em>Proceedings of the 16th International Conference on PErvasive Technologies Related to Assistive Environments</em> (2024), doi: <a href="https://doi.org/10.1145/3594806.3596555"><code>10.1145/3594806.3596555</code></a>
  links:
#    - name: PDF
#      url: 
#      icon: fa-solid fa-file-pdf
#      local: true
    - name: Final version
      url: https://doi.org/10.1145/3594806.3596555
      icon: fa-solid fa-scroll
#    - name: Code
#      url: 
#      icon: fa-brands fa-github
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1145/3594806.3596555
      icon: ai ai-zotero-square
#  extra: >- 
#    
doi: 10.1145/3594806.3596555
#haiku:
#  - 
#  - 
#  - 
---

## Abstract

Background: Indian classical music is categorized structurally and combinational and may benefit mental health. However, the psychological and physiological consequences of auditory stimuli like the Indian Classical ragas (a type of music) are less well known. Aim & Objective: To address the literature gap, this study aims to find the relaxation effects of classical Raga (Raga Bhairavi) in an immersive environment. Method: A within-group design study was performed with 22 participants following three interventions in the following order: Relaxed-baseline (paced breathing), Stress-baseline (using a mental arithmetic exam), and VR Raga (listening to classical music in an immersive environment). On the first day, all three interventions were delivered in order, while for the next six days, the Raga intervention was delivered only in virtual reality (VR) simulation. The participant's heart rate variability (HRV) was recorded during the intervention on the first and sixth days. Also, the Depression, Anxiety, and Stress Scale-21 (DASS-21) questionnaire was executed at the study's start (first day) and end (sixth day), respectively. Result: After six days of VR-based Raga intervention, the participants showed a significant reduction in the DASS-21 scores for stress, anxiety, and depression and significant improvement in the RR triangular index and reduction in the respiratory rate. We discuss how Raga interventions in VR could provide a conducive method for managing stress, anxiety, and depression.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1016/j.heliyon.2024.e32195">{{< ai zotero >}}&emsp;Add to Zotero {{< fa square-arrow-up-right >}}</a>
</p>

```bibtex
@inproceedings{chandra_impact_2023,
    title = {Impact of Indian Classical Raga in Immersive Environments on Human Psycho-physiological Parameters},
    author = {Chand, Kulbhushan and Chandra, Shilpa and Dutt, Varun},
    doi = {10.1145/3594806.3596555},
	  booktitle = {Proceedings of the 16th {International} {Conference} on {PErvasive} {Technologies} {Related} to {Assistive} {Environments}},
    year = {2023},
    pages = {746-753}}
```
