project:
  type: website
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

freeze: true

bibliography: files/bib/references.bib
#csl: 

# Metadata stuff
pagetitle: "{{< meta title >}} | Kulbhushan Chand"
author-meta: "Kulbhushan Chand"

website:
  title: "Kulbhushan Chand"
  description: "Kulbhushan Chand is a post doctoral fellow at Indian Institute of Technology Mandi, researching Human Computer Interaction"
#  favicon: 
  site-url: "https://kulbhushanchand.github.io"
  repo-url: "https://github.com/kulbhushanchand/kulbhushanchand.github.io"  


#  google-analytics: 

#  twitter-card: 
#    image: 
#    card-style: 
#    creator: 
#    site: 

#  open-graph: 
#    image: 
#    locale: 
    
    
  navbar:
    pinned: true
    
    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        file: "blog/index.qmd"
      - text: "Research"
        file: "research/index.qmd"
      - text: "Projects"
        file: "projects/index.qmd"        
      - text: "Now"
        href: "now/index.qmd"
      - text: "Uses"
        file: "uses/index.qmd"
      - text: "Contact"
        file: "contact/index.qmd"
        
    right:
      - text: "{{< iconify bi rss size=1.1em title='RSS' >}}"
        href: atom.xml
#      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
#        href: https://github.com/kulbhushanchand
#        rel: me
#      - text: "{{< iconify bi youtube size=1.1em title='YouTube' >}}"
#        href: https://www.youtube.com/kulbhushanchand
#        rel: me
#      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
#        href: https://www.linkedin.com/in/kulbhushan-chand/
#        rel: me

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Kulbhushan Chand</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)</span> 
      <span class="faux-block">[{{< iconify bi shield-exclamation >}} Disclaimer](/disclaimer/index.qmd)</span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
#      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss    
    grid: 
      body-width: 900px
    toc: false  
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai


