---
title: "Kb Rmd test"
output:
  md_document:
    pandoc_args: ["--wrap=none"]
    variant: gfm+footnotes
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  knitr::knit(inputFile, output = paste0('../_posts/',stringr::str_remove_all(inputFile, paste0(here::here(), '|', "/_source/", '|', "\\.Rmd")), '.md'));
  l = knitr::knit_meta();
  dep_dir = stringr::str_c(here::here(),'/assets/htmlwidgets_deps');
  base_path = stringr::str_c(here::here(),'/');
  includes_dir = "_includes/htmlwidgets/";
  hrefFilter = function(x) {paste0("/", x)};
  if (length(l) > 0) {dir.create(dep_dir, showWarnings = FALSE, recursive = TRUE)};
  l <- lapply(unique(l), function(dep) {
      dep <- htmltools::copyDependencyToDir(dep, dep_dir, FALSE);
      dep <- htmltools::makeDependencyRelative(dep, base_path, FALSE);
      dep } );
  l <- htmltools::renderDependencies(l,  hrefFilter=hrefFilter);
  render_markdown();
  prev_doc_hook <- knitr::knit_hooks$get("document");
  knitr::knit_hooks$set(document = function(x) {prev_doc_hook(append(x, l))});
  knitr::knit(inputFile, output = paste0('../_posts/',stringr::str_remove_all(inputFile, paste0(here::here(), '|', "/_source/", '|', "\\.Rmd")), '.md'))
  })
date: "16/02/2021"
excerpt: "Here are two tips for having what I think will be an easier blogging experience in R Markdown and Jekyll."
tags:
  - R Markdown
  - Jekyll
---

```{r setup, include=FALSE, cache=FALSE}
library(knitr)
library(stringr)
library(here)
# get name of file during knitting and strip file extension
rmd_filename <- str_remove(knitr::current_input(), "\\.Rmd")

# Figure path on disk = base.dir + fig.path
# Figure URL online = base.url + fig.path
knitr::opts_knit$set(base.dir = str_c(here::here(),'/'), base.url= '{{ site.url }}{{ site.baseurl }}/') # project root folder
knitr::opts_chunk$set(
	fig.path = str_c("assets/images/posts/", rmd_filename, "/"),
	message = FALSE,
	warning = FALSE,
	cache.path = "../cache/",
	dev = "svg",
	dpi = 72,
	screenshot.force = FALSE,
#	out.width = "100%",
#  fig.height = 4,
  fig.width = 8,
  fig.asp = 0.75,
	fig.cap = "",
  fig.align = "center"
)
```


---

# Initialization  
{: .text-center}


```{r echo=FALSE, message=FALSE}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gt)
library(formatR)
library(extrafont)
library(xkcd)
```

```{r echo=FALSE, message=FALSE}
#font_import()
#loadfonts(device = "win")
windowsFonts(Times = windowsFont("TT Times New Roman"))
```

## ggplot

```{r}
theme_set(theme_classic())

# Plot
g <- ggplot(mpg, aes(cty))
g + geom_density(aes(fill=factor(cyl)), alpha=0.8) + 
    labs(title="Density plot", 
         subtitle="City Mileage Grouped by Number of cylinders",
         caption="Source: mpg",
         x="City Mileage",
         fill="No. of Cylinders") +
  theme(text = element_text(size = 16, family = "xkcd"))
```

## leaflet

```{r fig.cap = "A map"}
library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map
```


## dt

```{r }
library(DT)
datatable(iris, options = list(pageLength = 5))
```

## plotly

```{r}
library(plotly)
d <- diamonds[sample(nrow(diamonds), 500), ]
plot_ly(d, x = d$carat, y = d$price, 
        text = paste("Clarity: ", d$clarity),
        mode = "markers", color = d$carat, size = d$carat)
```


