---
title: "Enhancing Tourism and Cultural Experience Through Gamification"
date: 2019-01-01
author:
  - name: Deepanshu Setia
    affiliation: National Institute of Technology Jalandhar, India
  - name: Rupinder Singh
    affiliation: National Institute of Technology Jalandhar, India
  - name: Amol Sharma
    affiliation: National Institute of Technology Jalandhar, India
  - name: Arun Khosla
    affiliation: National Institute of Technology Jalandhar, India
  - name: Kiran Ahuja
    affiliation: DAV Institute of Engineering and Technology, India
  - name: Kulbhushan Chand
    url: https://kulbhushanchand.github.io
    orcid: 0000-0003-2042-7063
    affiliation: National Institute of Technology Jalandhar, India

categories:
    - Gamification
    - Tourism enhancement
    - Cultural heritage
pub-info:
  reference: >-
    Deepanshu Setia, Rupinder Singh, Amol Sharma, Arun Khosla, Kiran Ahuja, and <strong>Kulbhushan Chand</strong>, “Enhancing Tourism and Cultural Experience Through Gamification,” chap. 7 in <em>Positioning and Branding Tourism Destinations for Global Competitiveness</em>, doi: <a href="https://doi.org/10.4018/978-1-5225-7253-4.ch007"><code>10.4018/978-1-5225-7253-4.ch007</code></a>
  links:
#  - name: Preprint (PDF)
#    url: 
#    local: true
#    icon: fa-solid fa-file-pdf
  - name: Final version
    url: https://doi.org/10.4018/978-1-5225-7253-4.ch007
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.4018/978-1-5225-7253-4.ch007
    icon: ai ai-zotero-square
doi: 10.4018/978-1-5225-7253-4.ch007
haiku:
  - Smartphones in our hands
  - Stories rise from ancient sands
  - Tourism expands
---

## Abstract

We all travel to different historical places but rarely notice the cultural significance of the place: the history behind the various things and locations. The primary aim of this chapter is to devise and develop means to enhance tourism and provide culturally important knowledge to people. Moreover, internet is booming, and the number of smartphones is increasing day by day. The same is happening in many developing countries. Therefore, in this chapter, the authors propose a criterion that uses technology to promote historical significance and enhances tourism industry as well. The proposed app uses the concept of gamification that acts as a platform to fuel the process of branding in a manner that engages the tourists and provide them with an experience that can make them feel more connected to the tourism destinations.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.4018/978-1-5225-7253-4.ch007">{{< ai zotero-square >}}&emsp;Add to Zotero {{< fa square-arrow-up-right >}}</a>
</p>

``` bibtex
@incollection{setia_enhancing_2019,
    title = {Enhancing {Tourism} and {Cultural} {Experience} {Through} {Gamification}},
    author = {Setia, Deepanshu and Singh, Rupinder and Sharma, Amol and Khosla, Arun and Ahuja, Kiran and Chand, Kulbhushan},
    doi = {10.4018/978-1-5225-7253-4.ch007},
    booktitle = {Positioning and {Branding} {Tourism} {Destinations} for {Global} {Competitiveness}},
    publisher = {IGI Global},
    year = {2019},
    chapter = {7},
    pages = {152-171}}
```
