---
title: "The Pursuit of Zero Food Waste: A Gamified Approach Promoting Avoidance of Dormitory Mess Food Wastage in Educational Institutions"
date: 2019-01-01
author:
  - name: Bhavika Jain
    affiliation: National Institute of Technology Jalandhar, India
  - name: Arun Khosla
    affiliation: National Institute of Technology Jalandhar, India
  - name: Kulbhushan Chand
    url: https://kulbhushanchand.github.io
    orcid: 0000-0003-2042-7063
    affiliation: National Institute of Technology Jalandhar, India
  - name: Kiran Ahuja
    affiliation: DAV Institute of Engineering and Technology, India
categories:
    - Gamification
    - Food waste reduction
    - Decision-making Method
pub-info:
  reference: >-
    Bhavika Jain, Arun Khosla, <strong>Kulbhushan Chand</strong>, and Kiran Ahuja, “The Pursuit of Zero Food Waste: A Gamified Approach Promoting Avoidance of Dormitory Mess Food Wastage in Educational Institutions,” chap. 13 in <em>Global Initiatives for Waste Reduction and Cutting Food Loss</em>, doi: <a href="https://doi.org/10.4018/978-1-5225-7706-5.ch013"><code>10.4018/978-1-5225-7706-5.ch013</code></a>
  links:
#  - name: Preprint (PDF)
#    url: 
#    local: true
#    icon: fa-solid fa-file-pdf
  - name: Final version
    url: https://doi.org/10.4018/978-1-5225-7706-5.ch013
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.4018/978-1-5225-7706-5.ch013
    icon: ai ai-zotero-square
doi: 10.4018/978-1-5225-7706-5.ch013
haiku:
  - Games ignite the spark
  - Students fight to leave a mark
  - Food waste fades in the dark
---

## Abstract

Games are ordered activities, generally undertaken for recreation. The design elements of these games are being used by people all around the planet to make this world a better place. The opportunities for gamification are being discussed in this chapter along with the use of a decision-making method as both have been applied to the study using a local running mobile application as platform for encouraging students enrolled in various educational institutions to promote avoidance of mess food wastage and in gaining confidence to integrate to use this approach to fight the cause of this global malady in their everyday life. The overarching issue of student mentality about food wastage is being discussed along with how to merge gamification with digital technology in this aspect and its participatory design. This provides the background for addressing points of using a gameful system to foster empowerment and connection among the students of NIT Jalandhar where this case was studied and the proposed approach was implemented.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.4018/978-1-5225-7706-5.ch013">{{< ai zotero-square >}}&emsp;Add to Zotero {{< fa square-arrow-up-right >}}</a>
</p>

``` bibtex
@incollection{jain_pursuit_2019,
    title = {The {Pursuit} of {Zero} {Food} {Waste}: {A} {Gamified} {Approach} {Promoting} {Avoidance} of {Dormitory} {Mess} {Food} {Wastage} in {Educational} {Institutions}},
    author = {Jain, Bhavika and Khosla, Arun and Chand, Kulbhushan and Ahuja, Kiran},
    doi = {10.4018/978-1-5225-7706-5.ch013},
    booktitle = {Global {Initiatives} for {Waste} {Reduction} and {Cutting} {Food} {Loss}},
    publisher = {IGI Global},
    year = {2019},
    chapter = {13},
    pages = {243-267}}
```
